### ISSUE TITLE
GitHub detected known vulnerability in jackson-databind

### ISSUE THREAD

**Issue by richardcardona** [pingidentity/status-servlet#6]
GitHub reports potential security vulnerability issues to administrators. This issue has been reported:

We found a potential security vulnerability in a repository for which you have been granted security alert access.

Known high severity security vulnerability detected in com.fasterxml.jackson.core:jackson-databind >= 2.7.0, < 2.7.9.1 defined in pom.xml.pom.xml update 

**suggested**: com.fasterxml.jackson.core:jackson-databind ~> 2.7.9.1.

Always verify the validity and compatibility of suggestions with your codebase

I would recommend at least version 2.7.9.4 within the same branch or 2.9.7 (if compatible).

**Comment by braveulysses** [comment]
Thanks, Richard. I've checked in a fix.
